# Site settings
title: "Git Large File Storage"
description: An open source Git extension for versioning large files
git-lfs-release: 1.2.0

url: "https://git-lfs.github.com"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

twitter:
  username: github

logo: /images/tweet-promo.png

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - script
